name: Forex_Scanner

on:
  schedule:
    - cron: '0 22 * * 1-5'   # 18:00 NY (EDT)
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run scanner
        env:
          Twelvedata_API_Key: ${{ secrets.TWELVEDATA_API_KEY }}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python scan_logic.py